// <auto-generated />
namespace ProWorldz.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27AugChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27AugChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201508271337014_27AugChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
